name: Feature Request
description: Suggest a new feature or improvement
labels: ['enhancement']
body:
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear description of the feature you'd like.
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Use Case / Motivation
      description: Why do you need this feature? What problem does it solve?
    validations:
      required: true

  - type: textarea
    id: proposed
    attributes:
      label: Proposed Solution
      description: How do you think this should work? (optional)
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any workarounds or alternatives? (optional)
    validations:
      required: false
